=== wowsonsun/frame/src/main/java/com/frame/core/query/xml/definition/pageDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="pageDefinition" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="pageDefinition">
    <xs:annotation>
      <xs:documentation>
        随便写写
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="queryDefinition" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:attribute name="showIndex"></xs:attribute>
            <xs:sequence minOccurs="1">
              <xs:element name="mappedClass">
                <xs:complexType>
                  <xs:attribute name="mappedClass" use="required"></xs:attribute>
                  <xs:attribute name="alias"></xs:attribute>
                  <xs:sequence minOccurs="0">
                    <xs:element name="join">
                      <xs:complexType>
                        <xs:attribute name="field" use="required"></xs:attribute>
                        <xs:attribute name="as"></xs:attribute>
                        <xs:attribute name="type">
                          <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                              <xs:enumeration value="LEFT"/>
                              <xs:enumeration value="INNER"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:sequence minOccurs="0">
              <xs:element name="where">
              </xs:element>
            </xs:sequence>
            <xs:sequence minOccurs="0">
              <xs:element name="sort">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="by">
                      <xs:complexType>
                        <xs:attribute name="field" use="required"></xs:attribute>
                        <xs:attribute name="fromAlias"></xs:attribute>
                        <xs:attribute name="order" use="required">
                          <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                              <xs:enumeration value="ASC"/>
                              <xs:enumeration value="DESC"/>
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:sequence minOccurs="1" maxOccurs="1">
              <xs:element name="columns">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="column">
                      <xs:complexType>
                        <xs:attribute name="field" use="required"></xs:attribute>
                        <xs:attribute name="header"></xs:attribute>
                        <xs:attribute name="fromAlias"></xs:attribute>
                        <xs:attribute name="width"></xs:attribute>
                        <xs:attribute name="sortable" type="xs:boolean"></xs:attribute>
                        <xs:attribute name="hidden" type="xs:boolean"></xs:attribute>
                        <xs:attribute name="filter"></xs:attribute>
                        <xs:attribute name="staticColumnData"></xs:attribute>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:sequence minOccurs="0" maxOccurs="1">
              <xs:element name="pageSize" type="xs:int">
              </xs:element>
            </xs:sequence>
            <xs:sequence maxOccurs="1" minOccurs="0">
              <xs:element name="js">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="path"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:sequence maxOccurs="1" minOccurs="0">
              <xs:element name="css">
                <xs:complexType>
                  <xs:sequence minOccurs="0">
                    <xs:element name="path"></xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:sequence maxOccurs="1" minOccurs="1">
              <xs:element name="searchDefinition" type="searchDefinitionType"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:sequence maxOccurs="1" minOccurs="0">
        <xs:element name="delete" type="deleteType"></xs:element>
      </xs:sequence>
      <xs:sequence maxOccurs="1" minOccurs="0">
        <xs:element name="manage">
          <xs:complexType>
            <xs:attribute name="beforeManage" default="beforeManage"/>
            <xs:sequence >
              <xs:element  name="field" type="manageType"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="searchDefinitionType">
    <xs:sequence minOccurs="1">
      <xs:element name="condition">
        <xs:complexType>
          <xs:attribute name="field" use="required"></xs:attribute>
          <xs:attribute name="alias"></xs:attribute>
          <xs:attribute name="operator" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:NMTOKEN">
                <xs:enumeration value="="></xs:enumeration>
                <xs:enumeration value="LIKE"></xs:enumeration>
                <!--<xs:enumeration value="BETWEEN"></xs:enumeration>-->
                <xs:enumeration value="&gt;"></xs:enumeration>
                <xs:enumeration value="&lt;"></xs:enumeration>
                <xs:enumeration value="&gt;="></xs:enumeration>
                <xs:enumeration value="&lt;="></xs:enumeration>
                <xs:enumeration value="!="></xs:enumeration>
                <xs:enumeration value="&lt;&gt;"></xs:enumeration>
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="defaultValue"></xs:attribute>
          <xs:attribute name="inputType" type="editorType">
          </xs:attribute>
          <xs:attribute name="displayText" use="required"></xs:attribute>
          <xs:attribute name="selectTextField"></xs:attribute>
          <xs:attribute name="selectValeField"></xs:attribute>
          <xs:attribute name="inputId"></xs:attribute>
          <xs:attribute name="optionClass"></xs:attribute>
          <xs:attribute name="nullable" type="xs:boolean">
          </xs:attribute>
          <xs:sequence minOccurs="0" maxOccurs="1">
            <xs:element name="staticData"></xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="editorType">
    <xs:restriction base="xs:NMTOKEN">
      <xs:enumeration value="TEXT"/>
      <xs:enumeration value="NUMBER"/>
      <xs:enumeration value="SELECT"/>
      <xs:enumeration value="DATEBOX"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="deleteType">
    <xs:attribute name="beforeDelete" default="beforeDelete"></xs:attribute>
  </xs:complexType>
  <xs:complexType name="manageType">
    <xs:attribute name="field" use="required"></xs:attribute>
    <xs:attribute name="defaultValue"></xs:attribute>
    <xs:attribute name="inputType" type="editorType">
    </xs:attribute>
    <xs:attribute name="displayText" use="required"></xs:attribute>
    <xs:attribute name="selectTextField"></xs:attribute>
    <xs:attribute name="selectValeField"></xs:attribute>
    <xs:attribute name="inputId"></xs:attribute>
    <xs:attribute name="optionClass"></xs:attribute>
    <xs:sequence minOccurs="0" maxOccurs="1">
      <xs:element name="staticData"></xs:element>
    </xs:sequence>
    <xs:attribute name="nullable" type="xs:boolean">
    </xs:attribute>
  </xs:complexType>
</xs:schema>

=== wowsonsun/frame/src/main/java/com/frame/webapp/controller/menu/pageDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.MenuEntity"
			alias="m" >
			<join field="parent" as="p" />
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" fromAlias="m" order="ASC"></by>
		</sort>
		<columns>
			<column header="ID" field="id" fromAlias="m" width="10%" sortable="true" hidden="false"></column>
			<column header="名称" field="displayName" fromAlias="m" width="20%" sortable="true" hidden="false"></column>
			<column header="父级" field="displayName" fromAlias="p" width="20%" sortable="false" hidden="false"></column>
			<column header="隐藏" field="hidden" fromAlias="m" width="10%" sortable="true" hidden="false"></column>
			<column header="URI" field="requestURI" fromAlias="m" width="30%" sortable="true" hidden="false"></column>
			<!-- <column header="操作" width="10%" sortable="false" hidden="false" staticColumnData="删除"></column> -->
		</columns>
		<searchDefinition>
			<condition alias="m" field="id" operator="=" displayText="ID" inputType="TEXT"></condition>
			<condition alias="p" field="id" operator="=" displayText="父级" selectTextField="displayName" inputType="SELECT"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
		<js><path>/a/b/c</path></js>
		<css><path>/a/b/c</path></css>
	</queryDefinition>
</pageDefinition>
